/**
 * QoS Discovery
 * # Overview The QoS Discovery API enables clients to query the connection info of QoS servers in their regions of interest. Clients can use these servers to measure each region's quality of service (QoS) and make informed decisions to provide the best experience.
 *
 * #####################################################################################
 *  Unity Gaming Services Plugin for Unreal Engine Copyright © 2025 Unity Technologies.
 * #####################################################################################
 * 
 * NOTE: This is a generated source file. Do not modify manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace RocketScienceQos
{

/*
 * OpenAPIErrorResponseBody
 *
 * 
 */
class ROCKETSCIENCEQOS_API OpenAPIErrorResponseBody : public Model
{
public:
    virtual ~OpenAPIErrorResponseBody() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028]). When this member is not present, its value is assumed to be \"about:blank\". */
	FString Type;
	/* A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization (e.g., using proactive content negotiation; see [RFC7231], Section 3.4). */
	FString Title;
	/* The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem. */
	int32 Status = 0;
	/* A service-specific error code. */
	int32 Code = 0;
	/* A human-readable explanation specific to this occurrence of the problem. */
	FString Detail;
	/* A URI reference that identifies the specific occurrence of the problem. It might or might not yield further information if dereferenced. */
	TOptional<FString> Instance;
	/* An array of machine-readable service-specific errors. */
	TOptional<TArray<TSharedPtr<FJsonObject>>> Details;
};

}
